name: Deploy .NET 8 to Azure

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Find appsettings.json
        run: find . -name "appsettings.json"

      - name: Debug appsettings.json Before Update
        run: cat NeuroTumAI.APIs/appsettings.json
      
      - name: Update appsettings.json
        run: |
          sed -i "s|\"DefaultConnection\": \"[^\"]*\"|\"DefaultConnection\": \"${{ secrets.DB_CONNECTION_STRING }}\"|" NeuroTumAI.APIs/appsettings.json
          sed -i "s|\"ValidIssuer\": \"[^\"]*\"|\"ValidIssuer\": \"${{ secrets.JWT_VALID_ISSUER }}\"|" NeuroTumAI.APIs/appsettings.json

      - name: Debug appsettings.json After Update
        run: cat NeuroTumAI.APIs/appsettings.json

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build and Publish
        run: dotnet publish -c Release -o ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "NeuroTumApi"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
